default_stages: [pre-commit, manual]

default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [build,bump,chore,ci,docs,feat,fix,hotfix,infr,merge,perf,refactor,revert,style,test]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: check-yaml
        args: ['--unsafe']
      - id: check-json
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=10700]
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        types_or: [python]
        args: [ --fix ]
      - id: ruff-format
        types_or: [python]
