[server]
headless = true
enableCORS=false
port = 80
[client]
showSidebarNavigation=false
[theme]
primaryColor="#218db1"
backgroundColor="#f0f0f5"
secondaryBackgroundColor="#e0e0ef"
textColor="#262730"
font="sans serif"
